title: Illogical Expressions
description: >
  A tech blog about all things bug bounty, security and development.
baseurl: ""
url: "https://ajxchapman.github.io"
twitter_username: ajxchapman
github_username: ajxchapman

gems:
  - jekyll-paginate
paginate: 5

excerpt_separator: <!--more-->

theme: jekyll-theme-cayman