title: Illogical Expressions
email: illogicalexpressions@noxr.net
description: >
  A tech blog about all things security, development, linux and illogical
  expressions.
baseurl: ""
url: "http://www.illogicalexpressions.com"
twitter_username: noxrnet
github_username: noxrnet

gems:
  - jekyll-paginate
paginate: 5

# Build settings
markdown: IEMarkdownIT

exclude:
  - vagrantfile
  - scripts

excerpt_separator: <!--more-->
