title: Alex Chapman's Blog
description: >
  A tech blog about all things bug bounty, security and development.
baseurl: ""
url: "https://ajxchapman.github.io"
twitter_username: ajxchapman
github_username: ajxchapman

plugins:
  - jekyll-paginate
  - jekyll-redirect-from

paginate: 5

excerpt_separator: <!--more-->

theme: jekyll-theme-cayman
