title: Alex Chapman's Blog
description: >
  A tech blog about all things bug bounty, security and development.
baseurl: ""
url: "https://ajxchapman.github.io"
twitter_username: ajxchapman
github_username: ajxchapman

plugins:
  - jekyll-paginate
  - jekyll-redirect-from

paginate: 10

excerpt_separator: <!--more-->
webstats:
    - endpoint: https://logs-01.loggly.com/inputs/c77487f5-9e26-4c31-bb3e-feb5c17a00e6/tag/loggly-jslogger
      method: POST
    - endpoint: https://www.google-analytics.com/collect
      id: UA-157572028-1

theme: jekyll-theme-cayman
collections:
  post_categories:
    output: true
    permalink: /:path/index.html
